#!/bin/bash

ODOO_VERSION=9.0
ODOO_URL=https://github.com/odoo/odoo/archive/$ODOO_VERSION.zip

if [ ! -f "$OPENSHIFT_DATA_DIR/odoo" ]; then
	# Instalación de prerrequisitos
        # Instalación de paquetes npm requeridos para less
        OLDHOME=$HOME
        HOME=$OPENSHIFT_REPO_DIR
        cd $HOME

        npm install errno
        npm install mkdirp
        npm install promise
        npm install mime
        npm install source-map
        npm install graceful-fs
        npm install less

        HOME=$OLDHOME
	# FIN Instalación de prerrequisitos

	# Instalación Odoo
	cd $OPENSHIFT_DATA_DIR

	echo "Odoo será descargado en breve"
	echo "URL: $ODOO_URL"
	wget $ODOO_URL -O $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}.zip
	unzip -o $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}.zip
	ln -s $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION} $OPENSHIFT_DATA_DIR/odoo
	source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate
	cd $OPENSHIFT_DATA_DIR/odoo
	# Se quita el paquete python-ldap de la instalación
	sed -i '/python-ldap/d' setup.py
	cd $OPENSHIFT_DATA_DIR/odoo
	# Odoo 9.0 requiere setuptool >= 1.4
	pip install https://pypi.python.org/packages/74/7c/c75c4f4032a4627406db06b742cdc7ba24c4833cd423ea7e22882380abde/setuptools-23.0.0-py2.py3-none-any.whl#md5=a066fd7bfb8faaad763acbdbcb290199
	
	python setup.py develop

	# FIN Instalación Odoo
fi
